SELECT CONVERT(VARCHAR(10), REPORTED_DATE, 112), OFFENSE_CATEGORY_ID
FROM dbo.denver_crime 
ORDER BY REPORTED_DATE

SELECT DATE, SNOW
FROM dbo.Denver_Precipitation$
WHERE DATE >= 20130101 and DATE < 20160503
ORDER BY DATE